[mattermost]
host = mattermost.uio.no
team = USIT-UIO
user = milen


# Set with: snap run --shell matterhorn -c 'secret-tool store --label="$SNAP_NAME" $SNAP_NAME <token>
#tokencmd = secret-tool lookup matterhorn token

urlOpenCommand = xdg-open

activityNotifyCommand = /home/milen/.config/matterhorn/notify

showTypingIndicator = True

enableAspell = True
aspellDictionary = "en"

[keybindings]
focus-next-unread = C-a
invoke-editor = C-k
toggle-multiline = F7
